# Generated by Django 5.0.1 on 2024-01-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="books.book",
            ),
        ),
    ]
